//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANcpLua.Analyzers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ANcpLua.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AL0001AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0001AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string AL0001AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0001AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string AL0001AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0001AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string AL0002AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0002AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string AL0002AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0002AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string AL0002AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0002AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string AL0003AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0003AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string AL0003AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0003AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string AL0003AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0003AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string AL0004AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0004AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string AL0004AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0004AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string AL0004AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0004AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string AL0005AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0005AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string AL0005AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0005AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string AL0005AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0005AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string AL0006AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0006AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string AL0006AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0006AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string AL0006AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0006AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string AL0007AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0007AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string AL0007AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0007AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string AL0007AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0007AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string AL0008AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0008AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string AL0008AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0008AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string AL0008AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0008AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string AL0009AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0009AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string AL0009AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0009AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string AL0009AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0009AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string AL0010AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0010AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string AL0010AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0010AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string AL0010AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0010AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string AL0011AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0011AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string AL0011AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0011AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string AL0011AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0011AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string AL0012AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0012AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string AL0012AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0012AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string AL0012AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0012AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string AL0013AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0013AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string AL0013AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0013AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string AL0013AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0013AnalyzerDescription", resourceCulture);
            }
        }

        internal static string AL0017AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0017AnalyzerTitle", resourceCulture);
            }
        }

        internal static string AL0017AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0017AnalyzerMessageFormat", resourceCulture);
            }
        }

        internal static string AL0017AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0017AnalyzerDescription", resourceCulture);
            }
        }

        internal static string AL0020AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0020AnalyzerTitle", resourceCulture);
            }
        }

        internal static string AL0020AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0020AnalyzerMessageFormat", resourceCulture);
            }
        }

        internal static string AL0020AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0020AnalyzerDescription", resourceCulture);
            }
        }

        internal static string AL0021AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0021AnalyzerTitle", resourceCulture);
            }
        }

        internal static string AL0021AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0021AnalyzerMessageFormat", resourceCulture);
            }
        }

        internal static string AL0021AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0021AnalyzerDescription", resourceCulture);
            }
        }

        internal static string AL0022AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0022AnalyzerTitle", resourceCulture);
            }
        }

        internal static string AL0022AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0022AnalyzerMessageFormat", resourceCulture);
            }
        }

        internal static string AL0022AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0022AnalyzerDescription", resourceCulture);
            }
        }

        internal static string AL0023AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0023AnalyzerTitle", resourceCulture);
            }
        }

        internal static string AL0023AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0023AnalyzerMessageFormat", resourceCulture);
            }
        }

        internal static string AL0023AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0023AnalyzerDescription", resourceCulture);
            }
        }

        internal static string AL0024AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0024AnalyzerTitle", resourceCulture);
            }
        }

        internal static string AL0024AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0024AnalyzerMessageFormat", resourceCulture);
            }
        }

        internal static string AL0024AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0024AnalyzerDescription", resourceCulture);
            }
        }

        internal static string AL0025AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0025AnalyzerTitle", resourceCulture);
            }
        }

        internal static string AL0025AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0025AnalyzerMessageFormat", resourceCulture);
            }
        }

        internal static string AL0025AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0025AnalyzerDescription", resourceCulture);
            }
        }

        internal static string AL0026AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0026AnalyzerTitle", resourceCulture);
            }
        }

        internal static string AL0026AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0026AnalyzerMessageFormat", resourceCulture);
            }
        }

        internal static string AL0026AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0026AnalyzerDescription", resourceCulture);
            }
        }

        internal static string AL0027AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0027AnalyzerTitle", resourceCulture);
            }
        }

        internal static string AL0027AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0027AnalyzerMessageFormat", resourceCulture);
            }
        }

        internal static string AL0027AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0027AnalyzerDescription", resourceCulture);
            }
        }


        internal static string AL0018AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0018AnalyzerTitle", resourceCulture);
            }
        }

        internal static string AL0018AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0018AnalyzerMessageFormat", resourceCulture);
            }
        }

        internal static string AL0018AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0018AnalyzerDescription", resourceCulture);
            }
        }


        internal static string AL0019AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0019AnalyzerTitle", resourceCulture);
            }
        }

        internal static string AL0019AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0019AnalyzerMessageFormat", resourceCulture);
            }
        }

        internal static string AL0019AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0019AnalyzerDescription", resourceCulture);
            }
        }

        internal static string AL0028AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0028AnalyzerTitle", resourceCulture);
            }
        }

        internal static string AL0028AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0028AnalyzerMessageFormat", resourceCulture);
            }
        }

        internal static string AL0028AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0028AnalyzerDescription", resourceCulture);
            }
        }

        internal static string AL0029AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0029AnalyzerTitle", resourceCulture);
            }
        }

        internal static string AL0029AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0029AnalyzerMessageFormat", resourceCulture);
            }
        }

        internal static string AL0029AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0029AnalyzerDescription", resourceCulture);
            }
        }

        internal static string AL0030AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0030AnalyzerTitle", resourceCulture);
            }
        }

        internal static string AL0030AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0030AnalyzerMessageFormat", resourceCulture);
            }
        }

        internal static string AL0030AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0030AnalyzerDescription", resourceCulture);
            }
        }

        internal static string AL0031AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL0031AnalyzerTitle", resourceCulture);
            }
        }

        internal static string AL0031AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL0031AnalyzerMessageFormat", resourceCulture);
            }
        }

        internal static string AL0031AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL0031AnalyzerDescription", resourceCulture);
            }
        }
    }
}

