//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANcpLua.Analyzers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ANcpLua.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string AL1000AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1000AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1000AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1000AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1000AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1000AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1001AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1001AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1001AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1001AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1001AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1001AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1002AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1002AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1002AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1002AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1002AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1002AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1003AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1003AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1003AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1003AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1003AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1003AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1004AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1004AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1004AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1004AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1004AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1004AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1005AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1005AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1005AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1005AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1005AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1005AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1006AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1006AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1006AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1006AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1006AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1006AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1007AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1007AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1007AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1007AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1007AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1007AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1008AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1008AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1008AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1008AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1008AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1008AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1009AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1009AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1009AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1009AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1009AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1009AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1600AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1600AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1600AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1600AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1600AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1600AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1601AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1601AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1601AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1601AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1601AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1601AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1602AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1602AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1602AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1602AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1602AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1602AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1100AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1100AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1100AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1100AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1100AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1100AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1101AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1101AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1101AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1101AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1101AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1101AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1102AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1102AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1102AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1102AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1102AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1102AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1103AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1103AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1103AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1103AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1103AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1103AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1104AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1104AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1104AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1104AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1104AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1104AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1700AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1700AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1700AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1700AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1700AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1700AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1701AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1701AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1701AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1701AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1701AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1701AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1702AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1702AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1702AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1702AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1702AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1702AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1703AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1703AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1703AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1703AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1703AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1703AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1200AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1200AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1200AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1200AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1200AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1200AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1201AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1201AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1201AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1201AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1201AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1201AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1202AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1202AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1202AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1202AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1202AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1202AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1203AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1203AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1203AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1203AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1203AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1203AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1204AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1204AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1204AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1204AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1204AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1204AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1205AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1205AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1205AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1205AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1205AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1205AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1206AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1206AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1206AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1206AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1206AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1206AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1207AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1207AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1207AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1207AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1207AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1207AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1208AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1208AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1208AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1208AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1208AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1208AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1209AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1209AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1209AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1209AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1209AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1209AnalyzerTitle", resourceCulture);
            }
        }
internal static string AL1210AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1210AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1210AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1210AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1210AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1210AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1211AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1211AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1211AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1211AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1211AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1211AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1400AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1400AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1400AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1400AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1400AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1400AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1401AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1401AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1401AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1401AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1401AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1401AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1402AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1402AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1402AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1402AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1402AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1402AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1403AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1403AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1403AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1403AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1403AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1403AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1212AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1212AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1212AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1212AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1212AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1212AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1213AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1213AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1213AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1213AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1213AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1213AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1214AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1214AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1214AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1214AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1214AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1214AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1215AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1215AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1215AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1215AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1215AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1215AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1216AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1216AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1216AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1216AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1216AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1216AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1217AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1217AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1217AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1217AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1217AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1217AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1218AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1218AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1218AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1218AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1218AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1218AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1404AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1404AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1404AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1404AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1404AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1404AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1405AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1405AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1405AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1405AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1405AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1405AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1603AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1603AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1603AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1603AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1603AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1603AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1604AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1604AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1604AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1604AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1604AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1604AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1605AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1605AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1605AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1605AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1605AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1605AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1300AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1300AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1300AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1300AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1300AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1300AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1301AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1301AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1301AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1301AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1301AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1301AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1302AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1302AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1302AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1302AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1302AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1302AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1303AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1303AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1303AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1303AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1303AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1303AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1105AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1105AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1105AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1105AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1105AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1105AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1106AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1106AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1106AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1106AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1106AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1106AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1107AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1107AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1107AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1107AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1107AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1107AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1108AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1108AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1108AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1108AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1108AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1108AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1406AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1406AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1406AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1406AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1406AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1406AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1407AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1407AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1407AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1407AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1407AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1407AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1408AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1408AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1408AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1408AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1408AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1408AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1409AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1409AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1409AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1409AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1409AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1409AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1304AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1304AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1304AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1304AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1304AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1304AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1305AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1305AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1305AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1305AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1305AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1305AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1109AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1109AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1109AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1109AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1109AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1109AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1306AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1306AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1306AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1306AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1306AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1306AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1307AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1307AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1307AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1307AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1307AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1307AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1308AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1308AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1308AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1308AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1308AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1308AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1309AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1309AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1309AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1309AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1309AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1309AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1310AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1310AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1310AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1310AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1310AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1310AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1311AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1311AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1311AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1311AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1311AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1311AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1312AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1312AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1312AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1312AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1312AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1312AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1501AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1501AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1501AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1501AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1501AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1501AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1502AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1502AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1502AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1502AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1502AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1502AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1503AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1503AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1503AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1503AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1503AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1503AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1504AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1504AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1504AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1504AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1504AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1504AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1505AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1505AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1505AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1505AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1505AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1505AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1219AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1219AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1219AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1219AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1219AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1219AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1220AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1220AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1220AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1220AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1220AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1220AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1313AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1313AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1313AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1313AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1313AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1313AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1314AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1314AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1314AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1314AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1314AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1314AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1606AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1606AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1606AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1606AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1606AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1606AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1800AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1800AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1800AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1800AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1800AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1800AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1801AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1801AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1801AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1801AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1801AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1801AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL1802AnalyzerDescription {
            get {
                return ResourceManager.GetString("AL1802AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL1802AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AL1802AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL1802AnalyzerTitle {
            get {
                return ResourceManager.GetString("AL1802AnalyzerTitle", resourceCulture);
            }
        }
    }
}
