//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANcpLua.Analyzers.CodeFixes {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeFixResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ANcpLua.Analyzers.CodeFixes.CodeFixResources", typeof(CodeFixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AL1001CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1001CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AL1003CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1003CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AL1004CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1004CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AR0001RefactoringTitle {
            get {
                return ResourceManager.GetString("AR0001RefactoringTitle", resourceCulture);
            }
        }
        
        internal static string AL1007CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1007CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AL1011CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1011CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AL1012CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1012CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1700CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1700CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1009CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1009CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1010CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1010CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1701CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1701CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1200CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1200CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1203CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1203CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1203CodeFixTitleTryGetConstantValue {
            get {
                return ResourceManager.GetString("AL1203CodeFixTitleTryGetConstantValue", resourceCulture);
            }
        }

        internal static string AL1702CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1702CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1201CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1201CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1202ImplementsCodeFixTitle {
            get {
                return ResourceManager.GetString("AL1202ImplementsCodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1202InheritsFromCodeFixTitle {
            get {
                return ResourceManager.GetString("AL1202InheritsFromCodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1210CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1210CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1204CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1204CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1205CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1205CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1206CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1206CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1207CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1207CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1208CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1208CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1209CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1209CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1211CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1211CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1212CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1212CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1213CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1213CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1214CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1214CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1215CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1215CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1216CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1216CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1217CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1217CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1218CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1218CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1500CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1500CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1503CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1503CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1504CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1504CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1313CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1313CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1220CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1220CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL1314CodeFixTitle {
            get {
                return ResourceManager.GetString("AL1314CodeFixTitle", resourceCulture);
            }
        }
    }
}
