//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace ANcpLua.Analyzers.CodeFixes;

using System;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
internal static class CodeFixResources
{
    private static global::System.Resources.ResourceManager? resourceMan;
    private static global::System.Globalization.CultureInfo? resourceCulture;

    internal static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ANcpLua.Analyzers.CodeFixes.CodeFixResources", typeof(CodeFixResources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    internal static global::System.Globalization.CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    internal static string AL0002CodeFixTitle => ResourceManager.GetString("AL0002CodeFixTitle", resourceCulture)!;
    internal static string AL0004CodeFixTitle => ResourceManager.GetString("AL0004CodeFixTitle", resourceCulture)!;
    internal static string AL0005CodeFixTitle => ResourceManager.GetString("AL0005CodeFixTitle", resourceCulture)!;
    internal static string AL0008CodeFixTitle => ResourceManager.GetString("AL0008CodeFixTitle", resourceCulture)!;
    internal static string AL0010CodeFixTitle => ResourceManager.GetString("AL0010CodeFixTitle", resourceCulture)!;
    internal static string AL0012CodeFixTitle => ResourceManager.GetString("AL0012CodeFixTitle", resourceCulture)!;
    internal static string AR0001RefactoringTitle => ResourceManager.GetString("AR0001RefactoringTitle", resourceCulture)!;
}
