//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANcpLua.Analyzers.CodeFixes {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeFixResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ANcpLua.Analyzers.CodeFixes.CodeFixResources", typeof(CodeFixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AL0002CodeFixTitle {
            get {
                return ResourceManager.GetString("AL0002CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AL0004CodeFixTitle {
            get {
                return ResourceManager.GetString("AL0004CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AL0005CodeFixTitle {
            get {
                return ResourceManager.GetString("AL0005CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AR0001RefactoringTitle {
            get {
                return ResourceManager.GetString("AR0001RefactoringTitle", resourceCulture);
            }
        }
        
        internal static string AL0008CodeFixTitle {
            get {
                return ResourceManager.GetString("AL0008CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AL0010CodeFixTitle {
            get {
                return ResourceManager.GetString("AL0010CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AL0012CodeFixTitle {
            get {
                return ResourceManager.GetString("AL0012CodeFixTitle", resourceCulture);
            }
        }
    }
}
