// Copyright (c) Alexander Nachtmann
// SPDX-License-Identifier: Apache-2.0

using System.Text;
using Microsoft.CodeAnalysis;

namespace ANcpLua.Analyzers.DocsGenerator;

// Intentionally an index, not an aggregate: each rule row links to its dedicated
// docs/rules/{id}_{symbolic}.md page, which is also where the descriptor's HelpLinkUri resolves.
internal static class IndexDocsRenderer
{
    public static string Render(
        IReadOnlyList<DiagnosticDescriptor> descriptors,
        HashSet<string> fixableIds,
        Dictionary<string, string> idToClass)
    {
        var sb = new StringBuilder();
        WriteHeader(sb);
        sb.AppendLine();
        WriteDiagnostics(sb, descriptors, fixableIds, idToClass);
        sb.AppendLine();
        WriteRelatedDocs(sb);
        sb.AppendLine();
        WriteGeneratedFile(sb);
        return sb.ToString().ReplaceLineEndings("\n");
    }

    private static void WriteHeader(StringBuilder sb)
    {
        sb.AppendLine($"# {RepoLayout.PackageName}");
        sb.AppendLine();
        sb.AppendLine($"<!-- <auto-generated /> This file is generated by {RepoLayout.ProjectRelativePath}. -->");
        sb.AppendLine();
        sb.AppendLine("Roslyn analyzers + code fixes covering modern C# correctness pitfalls, ASP.NET Core / Aspire patterns, Roslyn-utility hygiene, async/threading reliability, AOT/trim safety, package versioning, style, and agent-tool governance. Auto-injected by `ANcpLua.NET.Sdk` into every consuming project.");
        sb.AppendLine();
        sb.AppendLine("## Package family");
        sb.AppendLine();
        // renumber: post-2.0.0, AL ids live in AL10xx–AL18xx (sibling packages own AL0xxx).
        sb.AppendLine("- **[ANcpLua.Analyzers](https://github.com/ANcpLua/ANcpLua.Analyzers)** — this package; the `AL10xx`–`AL18xx` Roslyn diagnostics.");
        sb.AppendLine("- **[ANcpLua.NET.Sdk](https://github.com/ANcpLua/ANcpLua.NET.Sdk)** — MSBuild SDK that auto-injects this analyzer + the bundled `editorconfig` severity profile.");
        sb.AppendLine("- **[ANcpLua.Roslyn.Utilities](https://github.com/ANcpLua/ANcpLua.Roslyn.Utilities)** — shared Roslyn helpers + the `Guard.*` API the `AL12xx` band promotes.");
    }

    private static void WriteDiagnostics(
        StringBuilder sb,
        IReadOnlyList<DiagnosticDescriptor> descriptors,
        HashSet<string> fixableIds,
        Dictionary<string, string> idToClass)
    {
        sb.AppendLine("## Diagnostics");
        sb.AppendLine();
        sb.AppendLine("Each ID links to a per-rule page under [`docs/rules/`](rules/) with severity, category, code-fix status, and description. The descriptor's `HelpLinkUri` resolves to the same page, so IDE Quick-Fix \"Show error help\" lands on the focused rule, not on this index.");
        sb.AppendLine();
        sb.AppendLine("| ID | Severity | Title | Code fix |");
        sb.AppendLine("| -- | -- | -- | -- |");
        foreach (var d in descriptors)
        {
            var fix = fixableIds.Contains(d.Id) ? "Yes" : "No";
            var link = idToClass.TryGetValue(d.Id, out var className)
                ? $"[{d.Id}](rules/{d.Id}_{SymbolicNaming.ToSymbolicName(className)}.md)"
                : d.Id;
            sb.AppendLine($"| {link} | {d.DefaultSeverity} | {MarkdownFormatting.Escape(d.Title.ToString())} | {fix} |");
        }
    }

    private static void WriteRelatedDocs(StringBuilder sb)
    {
        sb.AppendLine("## Consumer-side severity profile (`AlAnalysisMode`)");
        sb.AppendLine();
        // renumber: post-2.0.0 band; bump if the AL bands shift again.
        sb.AppendLine("Set `<AlAnalysisMode>` in your csproj to switch the whole `AL10xx`–`AL18xx` band in one line instead of dropping editorconfig files:");
        sb.AppendLine();
        sb.AppendLine("```xml");
        sb.AppendLine("<PropertyGroup>");
        sb.AppendLine("  <AlAnalysisMode>AllAsErrors</AlAnalysisMode>");
        sb.AppendLine("</PropertyGroup>");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("| Value | Behavior |");
        sb.AppendLine("| -- | -- |");
        sb.AppendLine("| `Default` | Every rule at its descriptor-declared default severity. Useful to override an ambient stricter config (incl. ANcpLua.NET.Sdk's bundled profile). |");
        sb.AppendLine("| `AllAsErrors` | Every AL rule promoted to error. Use for strict CI. |");
        sb.AppendLine("| `Disabled` | Every AL rule silenced. |");
        sb.AppendLine("| _(unset)_ | No editorconfig injection. Inside an ANcpLua.NET.Sdk consumer, the SDK's bundled editorconfig still applies; outside it, descriptor severities apply. |");
        sb.AppendLine();
        sb.AppendLine("The property is exposed via the analyzer NuGet's `buildTransitive/ANcpLua.Analyzers.props`, which appends the matching editorconfig from `buildTransitive/editorconfig/` to `$(EditorConfigFiles)` on consumer restore. The name is deliberately not bare `<AnalysisMode>` — that property is owned by `Microsoft.CodeAnalysis.NetAnalyzers` and clashing would force consumers into one-or-the-other choices.");
        sb.AppendLine();
        sb.AppendLine("## See also");
        sb.AppendLine();
        // renumber: post-2.0.0 band references; bump if the AL bands shift again.
        sb.AppendLine("- [Per-rule pages](rules/) — one markdown file per `AL10xx`–`AL18xx` rule with severity, category, code-fix status, and description.");
        sb.AppendLine("- [Editorconfig profiles](editorconfig/) — three drop-in severity profiles: `Default`, `AllRulesAsErrors`, `AllRulesDisabled`. Same content ships inside the NuGet under `buildTransitive/editorconfig/`.");
        sb.AppendLine($"- [SARIF rule manifest]({RepoLayout.PackageName}.sarif) — SARIF v2.1.0 catalog of every `AL10xx`–`AL18xx` rule (id, name, severity, category, helpUri). Consume from Sonar bridges, GitHub Advanced Security uploads, or IDE rule-catalog tools.");
        sb.AppendLine("- [Migration catalog](migration-catalog.md) — the `AL0xxx` → `AL1xxx` rename map from the 2.0.0 break. Use to resolve stale `dotnet_diagnostic.AL0xxx.severity = …` editorconfig entries.");
        sb.AppendLine("- [`AnalyzerReleases.Shipped.md`](../src/ANcpLua.Analyzers/AnalyzerReleases.Shipped.md) / [`AnalyzerReleases.Unshipped.md`](../src/ANcpLua.Analyzers/AnalyzerReleases.Unshipped.md) — release-tracking manifest with `ClassName` attribution per Microsoft NetAnalyzers convention. Shipped rules are grouped under their release version; Unshipped holds rules pending the next release.");
    }

    private static void WriteGeneratedFile(StringBuilder sb)
    {
        sb.AppendLine("## Generated File");
        sb.AppendLine();
        sb.AppendLine("Regenerate with:");
        sb.AppendLine();
        sb.AppendLine("```bash");
        sb.AppendLine($"dotnet run --project {RepoLayout.ProjectRelativePath}              # rewrite docs + editorconfig profiles");
        sb.AppendLine($"dotnet run --project {RepoLayout.ProjectRelativePath} -- --check   # CI guard; fails if either is stale");
        sb.AppendLine($"dotnet run --project {RepoLayout.ProjectRelativePath} -- --audit   # print catalog statistics");
        sb.AppendLine("```");
    }
}
