// Copyright (c) Alexander Nachtmann
// SPDX-License-Identifier: Apache-2.0

using System.Text;

namespace ANcpLua.Analyzers.DocsGenerator;

/// <summary>
///   Renders <c>docs/migration-catalog.md</c>: the AL0xxx → AL1xxx rename map
///   from the 2.0.0 break. Consumer-facing answer to the question
///   "I have <c>dotnet_diagnostic.AL0001.severity = error</c> in my
///   editorconfig — what's it called now?".
///
///   Extension point: every section is a <c>void(StringBuilder, MigrationCatalogStats)</c>
///   in the <c>sections</c> array. New views (per-band severity heat-map, codefix
///   coverage column, etc.) plug in by appending to that array.
/// </summary>
internal static class MigrationCatalogRenderer
{
    public static string Render(MigrationCatalogStats stats)
    {
        var sb = new StringBuilder();
        var sections = new Action<StringBuilder, MigrationCatalogStats>[]
        {
            (b, _) => WriteHeader(b),
            WriteSummary,
            WriteCompletionAudit,
            WriteBandBreakdown,
            WriteRenameTable,
            (b, _) => WriteGeneratedFile(b),
        };

        foreach (var section in sections)
        {
            if (sb.Length > 0) sb.AppendLine();
            section(sb, stats);
        }

        return sb.ToString().ReplaceLineEndings("\n");
    }

    private static void WriteHeader(StringBuilder sb)
    {
        sb.AppendLine("# AL Analyzer Renumber Catalog");
        sb.AppendLine();
        sb.AppendLine($"<!-- <auto-generated /> This file is generated by {RepoLayout.ProjectRelativePath}. -->");
        sb.AppendLine();
        sb.AppendLine($"AL0xxx → AL1xxx rename map from the {RepoLayout.PackageName} 2.0.0 break. The 2.0.1 analyzer no longer emits any `AL0xxx` ID, so consumers carrying `dotnet_diagnostic.AL0xxx.severity = …` entries from an older version need this table to find the replacement.");
    }

    private static void WriteSummary(StringBuilder sb, MigrationCatalogStats stats)
    {
        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine($"`{stats.RenameCount}` rename{(stats.RenameCount == 1 ? "" : "s")} across `{stats.BandCount}` 100-wide domain band{(stats.BandCount == 1 ? "" : "s")}. The `AL0xxx` range is reserved for sibling packages (`ANcpLua.AotReflection`, `ANcpLua.ExtensibleEnumMirror`, `ANcpLua.DiscriminatedUnion`) and is not reissued by this analyzer.");
    }

    private static void WriteCompletionAudit(StringBuilder sb, MigrationCatalogStats _)
    {
        sb.AppendLine("## Completion audit");
        sb.AppendLine();
        sb.AppendLine("`AlIdMigrationCatalog.Validate()` enforces these invariants on every generator run + on every CI build (via `AnalyzerConventionTests.AlIdMigrationCatalog_StructuralInvariants_Hold`):");
        sb.AppendLine();
        sb.AppendLine("- No duplicate `OldId` across the catalog.");
        sb.AppendLine("- No duplicate `NewId` across the catalog.");
        sb.AppendLine("- Every `NewId` matches `^AL1[0-8]\\d{2}$` — sits inside the post-renumber band `AL1000..AL1899`.");
        sb.AppendLine("- Every `OldId` matches `^AL\\d{4}$` — well-formed legacy diagnostic ID.");
        sb.AppendLine();
        sb.AppendLine("No hardcoded `ExpectedCount` constant — count is a consequence of the invariants, not a property worth asserting on its own.");
    }

    private static void WriteBandBreakdown(StringBuilder sb, MigrationCatalogStats stats)
    {
        sb.AppendLine("## Renames by band");
        sb.AppendLine();
        sb.AppendLine("| Band | Count |");
        sb.AppendLine("| -- | --: |");
        foreach (var g in stats.Bands)
            sb.AppendLine($"| {g.Band} | {g.Count} |");
    }

    private static void WriteRenameTable(StringBuilder sb, MigrationCatalogStats _)
    {
        sb.AppendLine("## Old → New mapping");
        sb.AppendLine();
        sb.AppendLine("Sorted by `NewId` — scan to find your current ID's predecessor.");
        sb.AppendLine();
        sb.AppendLine("| Old ID | New ID | Title |");
        sb.AppendLine("| -- | -- | -- |");
        foreach (var e in AlIdMigrationCatalog.Entries.OrderBy(x => x.NewId, StringComparer.Ordinal))
            sb.AppendLine($"| `{e.OldId}` | `{e.NewId}` | {MarkdownFormatting.Escape(e.Title)} |");
    }

    private static void WriteGeneratedFile(StringBuilder sb)
    {
        sb.AppendLine("## Generated file");
        sb.AppendLine();
        sb.AppendLine("Regenerate with:");
        sb.AppendLine();
        sb.AppendLine("```bash");
        sb.AppendLine($"dotnet run --project {RepoLayout.ProjectRelativePath}              # rewrite docs + editorconfig profiles + migration-catalog");
        sb.AppendLine($"dotnet run --project {RepoLayout.ProjectRelativePath} -- --check   # CI guard; fails if anything is stale");
        sb.AppendLine($"dotnet run --project {RepoLayout.ProjectRelativePath} -- --audit   # print catalog statistics");
        sb.AppendLine("```");
    }
}

/// <summary>
///   Computed view of <see cref="AlIdMigrationCatalog"/>. <see cref="Compute"/> also
///   calls <see cref="AlIdMigrationCatalog.Validate"/> so any contract drift fails
///   before we start writing files. Mirrors the QYL <c>CatalogStatistics</c> shape
///   for cross-repo familiarity.
/// </summary>
internal sealed record MigrationCatalogStats(
    int RenameCount,
    int BandCount,
    IReadOnlyList<(string Band, int Count)> Bands)
{
    public static MigrationCatalogStats Compute()
    {
        AlIdMigrationCatalog.Validate();
        var bands = AlIdMigrationCatalog.Entries
            .GroupBy(e => e.Band, StringComparer.Ordinal)
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .Select(g => (Band: g.Key, Count: g.Count()))
            .ToArray();
        return new MigrationCatalogStats(
            RenameCount: AlIdMigrationCatalog.Entries.Length,
            BandCount: bands.Length,
            Bands: bands);
    }

    public string RenderAudit()
    {
        var sb = new StringBuilder();
        sb.AppendLine($"AL ID migration catalog audit");
        sb.AppendLine($"  Total renames: {RenameCount}");
        sb.AppendLine($"  Domain bands:  {BandCount}");
        foreach (var (band, count) in Bands)
            sb.AppendLine($"    {band,-40}  {count}");
        return sb.ToString();
    }
}
