// Copyright (c) Alexander Nachtmann
// SPDX-License-Identifier: Apache-2.0

using System.Text;
using Microsoft.CodeAnalysis;

namespace ANcpLua.Analyzers.DocsGenerator;

// One small markdown page per rule, so IDE Quick-Fix "Show error help" resolves onto a focused
// page rather than a multi-thousand-line aggregate.
internal static class RulePageRenderer
{
    public static string Render(
        DiagnosticDescriptor descriptor,
        string className,
        HashSet<string> fixableIds)
    {
        var sb = new StringBuilder();
        var title = MarkdownFormatting.Escape(descriptor.Title.ToString());
        var description = MarkdownFormatting.Escape(descriptor.Description.ToString());
        var codeFix = fixableIds.Contains(descriptor.Id) ? "Yes" : "No";
        var sourceBasename = SymbolicNaming.FileBasenameForClass(className);

        sb.AppendLine($"# {descriptor.Id}: {title}");
        sb.AppendLine();
        sb.AppendLine($"<!-- <auto-generated /> This file is generated by {RepoLayout.ProjectRelativePath}. -->");
        sb.AppendLine();
        sb.AppendLine("| Property | Value |");
        sb.AppendLine("| -- | -- |");
        sb.AppendLine($"| Severity | {descriptor.DefaultSeverity} |");
        sb.AppendLine($"| Category | `{descriptor.Category}` |");
        sb.AppendLine($"| Code fix | {codeFix} |");
        sb.AppendLine($"| Analyzer | `{className}` |");
        sb.AppendLine($"| Enabled by default | {(descriptor.IsEnabledByDefault ? "Yes" : "No")} |");
        sb.AppendLine();
        sb.AppendLine("## Description");
        sb.AppendLine();
        sb.AppendLine(description);
        sb.AppendLine();
        sb.AppendLine("## See also");
        sb.AppendLine();
        sb.AppendLine($"- [Rule index](../{RepoLayout.PackageName}.md)");
        sb.AppendLine($"- [Source: `{sourceBasename}.cs`](../../src/{RepoLayout.PackageName}/Analyzers/{sourceBasename}.cs)");
        return sb.ToString().ReplaceLineEndings("\n");
    }
}
