// Copyright (c) Alexander Nachtmann
// SPDX-License-Identifier: Apache-2.0

using System.Text;
using Microsoft.CodeAnalysis;

namespace ANcpLua.Analyzers.DocsGenerator;

/// <summary>
///   Emits one markdown page per rule, keyed by id + symbolic name. Each page is
///   small (header + property table + description + see-also) so IDE Quick-Fix
///   "Show error help" links resolve onto a focused page rather than the
///   multi-thousand-line aggregate.
///
///   Extension point: per-rule examples sourced from the analyzer test fixtures land
///   here once a fixture-extraction helper exists — the scenario-docs scaffold in
///   <c>src/ANcpLua.Analyzers.AnalyzerDocs/</c> is the architectural target.
/// </summary>
internal static class RulePageRenderer
{
    public static string Render(
        DiagnosticDescriptor descriptor,
        string className,
        HashSet<string> fixableIds)
    {
        var sb = new StringBuilder();
        var title = MarkdownFormatting.Escape(descriptor.Title.ToString());
        var description = MarkdownFormatting.Escape(descriptor.Description.ToString());
        var codeFix = fixableIds.Contains(descriptor.Id) ? "Yes" : "No";
        var sourceBasename = SymbolicNaming.FileBasenameForClass(className);

        sb.AppendLine($"# {descriptor.Id}: {title}");
        sb.AppendLine();
        sb.AppendLine($"<!-- <auto-generated /> This file is generated by {RepoLayout.ProjectRelativePath}. -->");
        sb.AppendLine();
        sb.AppendLine("| Property | Value |");
        sb.AppendLine("| -- | -- |");
        sb.AppendLine($"| Severity | {descriptor.DefaultSeverity} |");
        sb.AppendLine($"| Category | `{descriptor.Category}` |");
        sb.AppendLine($"| Code fix | {codeFix} |");
        sb.AppendLine($"| Analyzer | `{className}` |");
        sb.AppendLine($"| Enabled by default | {(descriptor.IsEnabledByDefault ? "Yes" : "No")} |");
        sb.AppendLine();
        sb.AppendLine("## Description");
        sb.AppendLine();
        sb.AppendLine(description);
        sb.AppendLine();
        sb.AppendLine("## See also");
        sb.AppendLine();
        sb.AppendLine($"- [Rule index](../{RepoLayout.PackageName}.md)");
        sb.AppendLine($"- [Source: `{sourceBasename}.cs`](../../src/{RepoLayout.PackageName}/Analyzers/{sourceBasename}.cs)");
        return sb.ToString().ReplaceLineEndings("\n");
    }
}
